# Generated by Django 4.2.7 on 2023-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_variation_category'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_added'], 'verbose_name': 'Carrito'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Carrito Item', 'verbose_name_plural': 'Carrito Items'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
